name: Deploy Staging Site

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
            CI: false
            REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
            NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

      - name: Create .htaccess
        run: |
          echo "RewriteEngine On" > build/.htaccess
          echo "RewriteBase /" >> build/.htaccess
          echo "RewriteRule ^index\.html$ - [L]" >> build/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-f" >> build/.htaccess
          echo "RewriteCond %{REQUEST_FILENAME} !-d" >> build/.htaccess
          echo "RewriteRule . /index.html [L]" >> build/.htaccess

      - name: Deploy to Staging
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_STAGING }}
          password: ${{ secrets.FTP_PASSWORD_STAGING }}
          local-dir: ./build/
          server-dir: /public_html/staging/
          dangerous-clean-slate: true
          port: 21
          security: strict