name: Deploy to Staging

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build Production
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}

      - name: Deploy to Production
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD_PROD }}
          local-dir: ./build/
          server-dir: /
          protocol: ftp
          security: loose
          timeout: 120000
          exclude: |
            **/.git*/**
            **/.git*/**
            **/node_modules/**